version: '2'
services:

  lookupservice:
    image: gioargyr/lookup-service:1.0.0
    ports:
      - "8190:8080"
    networks:
      - default

  imageaggregator:
    image: gioargyr/image-aggregator:1.0.0
    volumes:
      - /home/iitadmin/imageaggregator:/images
    ports:
      - "12345:8080"
    networks:
      - default

  postgis:
    image: bde2020/postgis
    volumes:
      - /srv/postgis:/var/lib/postgresql/9.4/main
    ports:
      - "5432:5432"
    networks:
      - default

  strabon:
    image: bde2020/strabon
    ports:
      - "8191:8080"
    depends_on:
      - postgis
    networks:
      - default
    
  semagrow:
    image: semagrow/semagrow-cassandra
    ports:
      - "8192:8080"
    volumes:
      - ./config/semagrow:/etc/default/semagrow
    depends_on:
      - strabon
    networks:
      - default
      
  geotriples:
    image: gioargyr/docker-geotriples-ws:1.0.0
    ports:
      - "8193:8080"
    depends_on:
      - strabon
    networks:
      - default

  master:
    image: bde2020/spark-master:1.5.1-hadoop2.6
    hostname: spark-master
    environment:
      - INIT_DAEMON_STEP:spark_master_init
      - VIRTUAL_HOST:spark-master.iit.demokritos.gr
      - VIRTUAL_PORT:8080
    ports:
      - "8290:8080"
    volumes:
      - ./data/spark-master:/data
    networks:
      - default

  worker1:
    image: bde2020/spark-worker:1.5.1-hadoop2.6
    environment:
      - VIRTUAL_HOST:spark-worker1.iit.demokritos.gr
      - VIRTUAL_PORT:8081
    depends_on:
      - master
    networks:
      - default

  worker2:
    image: bde2020/spark-worker:1.5.1-hadoop2.6
    environment:
      - VIRTUAL_HOST:spark-worker2.iit.demokritos.gr
      - VIRTUAL_PORT:8082
    depends_on:
      - master
    networks:
      - default

  worker3:
    image: bde2020/spark-worker:1.5.1-hadoop2.6
    environment:
      - VIRTUAL_HOST:spark-worker3.iit.demokritos.gr
      - VIRTUAL_PORT:8083
    depends_on:
      - master
    networks:
      - default

  worker4:
    image: bde2020/spark-worker:1.5.1-hadoop2.6
    environment:
      - VIRTUAL_HOST:spark-worker4.iit.demokritos.gr
      - VIRTUAL_PORT:8084
    depends_on:
      - master
    networks:
      - default

  changedetector:
    image: gioargyr/pilot-sc7-change-detector:1.0.0
    environment:
      - INIT_DAEMON_STEP:detect_changes
    volumes:
      - /home/iitadmin/imageaggregator:/inputimages
    depends_on:
      - master
    networks:
      - default

  integratorui:
    image: bde2020/integrator-ui:latest
    environment:
      - VIRTUAL_HOST:iit.demokritos.gr
    ports:
      - "8390:80"
    volumes:
      - ./config/integrator:/app/config
    networks:
      - default

  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    volumes:
      - ./config:/config
    networks:
      - default

  identifier:
    image: semtech/mu-identifier:1.0.0
    networks:
      - default

  monitor:
    image: bde2020/pipeline-monitor-frontend:0.1.0
    environment:
      - VIRTUAL_HOST:monitor.iit.demokritos.gr
    ports:
      - "8391:80"
    links:
      - identifier:backend
    networks:
      - default

  initdaemon:
    image: bde2020/mu-init-daemon-service:0.1.0
    networks:
      - default

  pipeline:
    image: bde2020/mu-pipeline-service:0.1.0
    networks:
      - default

  database:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.2
    environment:
      - SPARQL_UPDATE:"true"
      - DEFAULT_GRAPH:http://mu.semte.ch/application
      - VIRTUAL_HOST:virtuoso.iit.demokritos.gr
      - VIRTUAL_PORT:8890
    volumes:
      - ./data/db/toLoad:/data
    ports:
      - "8890:8890"
    networks:
      - default

networks:
  default:
    external:
      name: bde_net
